services:
  - type: web
    name: rohis-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false  
      - key: FRONTEND_ORIGIN
        value: https://managespace-rohis.vercel.app
      - key: GROQ_API_KEY
        sync: false
      - key: CRON_SECRET_TOKEN
        generateValue: true
      - key: MAILJET_API_KEY
        sync: false
      - key: MAILJET_API_SECRET
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false